version: '3.8'
services:
  client-spa:
    network_mode: "host"
    # image: react-spa-webwbd
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client-spa-webwbd-2
    ports:
      - '5173:5173'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true